Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2019
Var
// Seção de Declarações das variáveis 
larg, comp, area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Informe o comprimento: ")
leia (comp)

escreva ("Informe a largura: ")
leia (larg)

area <- larg * comp

escreval ( "A area é: ", area, "m²")

Fimalgoritmo