Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/08/2019
Var


BASE,ALTURA,AREA: real

Inicio
escreva ("Digite a base: ")
leia (BASE)

escreva ("Digite a altura: ")
leia (ALTURA)

AREA <- BASE * ALTURA / 2
escreva ("area: " , AREA)




Fimalgoritmo