Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2019
Var
// Seção de Declarações das variáveis 
nome: caracter
idade: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Informe o nome: ")
leia (nome)

escreva ("Informe a idade: ")
leia (idade)

escreval ("O nome é: ", nome)
escreval ("E a idade é: ", idade)

Fimalgoritmo