Algoritmo "MAIOR IDADE"
//  
//  
//  Data atual  : 23/09/2019
Var
// Seção de Declarações das variáveis 
  idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva ("Digite sua idade: ")
  leia (idade)
  
  se   (idade >=18) entao
  escreva ("VOCÊ É MAIOR DE 18 ANOS")
          senao
          escreva ("VOCÊ É MENOR DE IDADE")
  FIMSE
Fimalgoritmo