Algoritmo "SENHA"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2019
Var
// Seção de Declarações das variáveis 

senha: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva ("DIGITE SUA SENHA: ")
leia (senha)

se ( senha = 4567) entao
escreva ("SENHA AUTORIZADA")

     senao
     escreva ("ACESSO NEGADO")
FIMSE

Fimalgoritmo