Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/11/2019
Var
// Seção de Declarações das variáveis 
v: vetor[1..10] de inteiro
i, n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i:=1 ate 10 faca
escreval("Digite o ",i," valor desejado")
leia(n)
fimpara

Fimalgoritmo