Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2019
Var
// Seção de Declarações das variáveis 
n1: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite um valor:")
   Leia (n1)
   Se (n1 % 2 = 0) entao
      Escreval ("O número é par: ")
   Senao
      Escreva ("O número é ímpar: ")
   FimSe

Fimalgoritmo